#!/usr/bin/env bash

RED='\033[0;31m'
GRN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'
# Check current versions
status (){

        printf "${BOLD}%-15s%-15s%-25s%-25s${NC}\n" "Service" "State" "Installed" "Available"

        SERVICE=$(svcs -H -oSVC,STATE sniffle howl snarl 2>/dev/null | awk '{print substr($0,index($0,"/")+1)}')

        current=$(/opt/local/bin/python /etc/fifo_current_version.py)
        while read ASERVICE
        do

                PKG=$(echo "$ASERVICE" | awk '{print $1}')
                version=$(cat /opt/local/fifo-${PKG}/releases/start_erl.data  | awk '{ print $2 }')
                if [[ $current == *"pkg/rel/fifo-${PKG}-$version"* ]]
                        then
                                printf "%-15s%-15s${GRN}%-25s%-25s${NC}\n" ${ASERVICE} "${PKG}-${version}" "${version}"
                        else
                                needed=$(echo "${current}" | grep pkg/rel/fifo-${PKG} | rev | cut -d- -f1 | rev)
                                printf "%-15s%-15s${RED}%-25s%-25s${NC}\n" ${ASERVICE} "${PKG}-${version}" "${needed}"
                        fi

        done <<< "$SERVICE"

}

#sed -e 's/#/'$(echo -e "\033")'[0;34m#'$(echo -e "\033")'[0m/g' -e 's/\*/'$(echo -e "\033")'[1;37m*'$(echo -e "\033")'[0m/g' cloud
cat <<EOF
    ____               _           __     _______ ______
   / __ \_________    (_)__  _____/ /_   / ____(_) ____/___
  / /_/ / ___/ __ \  / / _ \/ ___/ __/  / /_  / / /_  / __ \
 / ____/ /  / /_/ / / /  __/ /__/ /_   / __/ / / __/ / /_/ /
/_/   /_/   \____/_/ /\___/\___/\__/  /_/   /_/_/    \____/
                /___/        Delicate Dane
EOF

status